### ISSUE TITLE
TerminalReporter with "showStack: true" show a lot of noise

### ISSUE THREAD

**Issue by DanielSundberg** [larrymyers/jasmine-reporters#108]
I have the following spec: 

var foo = 'bar';
expect(foo).toEqual('foo');

Jasmine executed from gulp with terminal reporter set to "showStack: true".

I get a lot of noise in the stack trace, only one single line is of interest to me.

<pre>
TestSpec should give correct result
    Expected 'bar' to equal 'foo'.
    Error: Expected 'bar' to equal 'foo'.
</pre>
<code>
        at stack (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1482:17)

        at buildExpectationResult (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1452:14)
        at Spec.Env.expectationResultFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:583:18)
        at Spec.addExpectationResult (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:324:34)
        at Expectation.addExpectationResult (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:533:21)
        at Expectation.toEqual (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1406:12)
        at Object.<anonymous> (c:\code\static\tests\CaseStore.test.js:13211:21)
        at attemptSync (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1789:24)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1777:9)
        at QueueRunner.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1762:10)
        at Spec.Env.queueRunnerFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:627:35)
        at Spec.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:353:10)
        at Object.fn (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2360:37)
        at attemptAsync (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at QueueRunner.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1762:10)
        at Env.queueRunnerFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:627:35)
        at Object.fn (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2345:13)
        at attemptAsync (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16
        at c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9
        at queueRunnerFactory.onComplete (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2348:17)
        at QueueRunner.clearStack (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:605:9)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1784:12)
        at c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16
        at c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9
        at complete (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:365:9)
        at QueueRunner.clearStack (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:605:9)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1784:12)
        at QueueRunner.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1762:10)
        at Spec.Env.queueRunnerFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:627:35)
        at Spec.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:353:10)
        at Object.fn (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2360:37)
        at attemptAsync (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16
        at c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9
        at complete (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:365:9)
        at QueueRunner.clearStack (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:605:9)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1784:12)
        at QueueRunner.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1762:10)
        at Spec.Env.queueRunnerFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:627:35)
        at Spec.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:353:10)
        at Object.fn (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2360:37)
        at attemptAsync (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at QueueRunner.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1762:10)
        at Env.queueRunnerFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:627:35)
        at Object.fn (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2345:13)
        at attemptAsync (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at QueueRunner.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1762:10)
        at Env.queueRunnerFactory (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:627:35)
        at TreeProcessor.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2209:7)
        at Env.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:678:17)
        at Jasmine.execute (c:\code\node_modules\gulp-jasmine\node_modules\jasmine\lib\jasmine.js:160:12)
        at DestroyableTransform._flush (c:\code\node_modules\gulp-jasmine\index.js:72:12)
        at DestroyableTransform.<anonymous> (c:\code\node_modules\gulp-jasmine\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
        at DestroyableTransform.g (events.js:199:16)
        at DestroyableTransform.emit (events.js:129:20)
        at finishMaybe (c:\code\node_modules\gulp-jasmine\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
        at endWritable (c:\code\node_modules\gulp-jasmine\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
        at DestroyableTransform.Writable.end (c:\code\node_modules\gulp-jasmine\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
        at DestroyableTransform.onend (c:\code\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
        at DestroyableTransform.g (events.js:199:16)
        at DestroyableTransform.emit (events.js:129:20)
        at c:\code\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
        at process._tickCallback (node.js:355:11)

</code>

**Comment by bloveridge** [comment]
The stack trace comes from the Jasmine library, all TerminalReporter does is log it out with the correct indent level (and optionally `magenta`). TerminalReporter does not try to parse the stack and be selective about inclusion / exclusion. You could consider pursuing ways of trimming down the stack trace Jasmine includes on expectation failures, but there are currently no plans for jasmine-reporters to try and understand stack trace specifics.
