### ISSUE TITLE
Incompatible with gulp-jasmine-browser

### ISSUE THREAD

**Issue by ActuallyDidIt** [larrymyers/jasmine-reporters#162]
When trying to use gulp-jasmine-browser, any failures triggers (with it appears to be all reporters) this error: 

> TypeError: Cannot read property '_failures' of undefined
    at self.specDone (...node_modules\jasmine-reporters\src\nunit_reporter.js:155:28)
    at ...node_modules\jasmine-json-stream-reporter\to-reporter.js:55:48
    at Array.forEach (native)
    at ...node_modules\jasmine-json-stream-reporter\to-reporter.js:54:17
    at Array.find (native)
    at DestroyableTransform._transform (...node_modules\jasmine-json-stream-reporter\to-reporter.js:50:25)
    at DestroyableTransform.Transform._read (...node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (...node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (...node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (...node_modules\readable-stream\lib\_stream_writable.js:336:5)

Digging a little deeper, it appears the internal `suite` variable is never available. Not sure if there's an easy work around for this or if I'm doing anything wrong.

gulpfile.js:
```
const` gulp = require('gulp');
const jasmineBrowser = require('gulp-jasmine-browser');
const reporters = require('jasmine-reporters');

gulp.task('test', function () {
    return gulp.src(['scripts/lib/*.js', 'scripts/dist/test.bundle.js'])
        .pipe(jasmineBrowser.specRunner({ console: true }))
        .pipe(jasmineBrowser.headless({
            reporter: [
                new reporters.NUnitXmlReporter({
                    savePath: '.',
                    consolidateAll: false
                })
            ]
       }));
});
```

node v5.4.1, npm v3.3.4, gulp 3.9.1, gulp-jasmine-browser 1.7.1, jasmine-reporters 2.2.0

**Comment by bloveridge** [comment]
Were you ever able to find a solution to this issue?
