### ISSUE TITLE
Error on jasmine-node side

### ISSUE THREAD

**Issue by nirkoren** [larrymyers/jasmine-reporters#63]
Hi,

we get this error (TeamCity reporter) :

/home/panda/panda_git/internal/on_demand/automation/jasmine/nodejs/node_modules/jasmine-node/lib/jasmine-node/reporter.js:336
  jasmineNode.TeamcityReporter.prototype = new jasmine.TeamcityReporter;
                                           ^
TypeError: undefined is not a function
    at /home/panda/panda_git/internal/on_demand/automation/jasmine/nodejs/node_modules/jasmine-node/lib/jasmine-node/reporter.js:336:44
    at Object.<anonymous> (/home/panda/panda_git/internal/on_demand/automation/jasmine/nodejs/node_modules/jasmine-node/lib/jasmine-node/reporter.js:342:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/panda/panda_git/internal/on_demand/automation/jasmine/nodejs/node_modules/jasmine-node/lib/jasmine-node/index.js:34:21)
    at Module._compile (module.js:456:26)
[INFO] ---------------------------------------------
# 

More info here:
http://stackoverflow.com/questions/24553915/jasmine-node-shows-error-when-ran-from-command-prompt

**Comment by cscleison** [comment]
It's case sensitive. Try ```new jasmineReporters.TeamCityReporter()```
